Biblioteca/Controllers/BookController.cs
using Biblioteca.Services;
using Biblioteca.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Biblioteca.Controllers
{
    public class BookController : Controller

    {
        private readonly BookServices _bookServices;

        public BookController(BookServices bookServices)
        {
            _bookServices = bookServices;
        }
        public async Task<IActionResult> Index()
        {
            var booksList = await _bookServices.GetAllBooksAsync();

            return View(booksList);
        }

     
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddBookViewModel addBookViewModel)
        {
            if (!ModelState.IsValid)
            {
                TempData["Error"] = "Error while saving entity to database";
                return RedirectToAction("Index");
            }
            var result = await _bookServices.AddBookAsync(addBookViewModel);
            if (!result)
            {
                TempData["Error"] = "Error while saving entity to database";
            }
            return RedirectToAction("Index");
        }

        [Route("book/details/{id:guid}")]
        public async Task<IActionResult> Details(Guid id)
        {
            var book = await _bookServices.GetBookByIdAsync(id);
            if (book == null)
            {
                TempData["Error"] = "Error while finding entity on database";
                return RedirectToAction("Index");
            }
      
            var bookDetailsViewModel = new BookDetailsViewModel()
            {
                Id = book.Id,
                Title = book.Title,
                Author = book.Author,
                Genre = book.Genre,
                Availability = book.Availability,
                ImgCover = book.ImgCover,
            };

            return View(bookDetailsViewModel);
        }

        public async Task<IActionResult> Delete(Guid id)
        {
            var result = await _bookServices.DeleteBookByIdAsync(id);

            if (!result)
            {
                TempData["Error"] = "Error while deleting entity from database";
            }
            return RedirectToAction("Index");
        }

        public async Task <IActionResult> Edit (Guid id)
        {
            var book = await _bookServices.GetBookByIdAsync(id);

            if (book == null) { return RedirectToAction("Index"); };

            var editBookViewModel = new EditBookViewModel()
            {
                Id = book.Id,
                Title = book.Title,
                Author = book.Author,
                Genre = book.Genre,
                Availability = book.Availability,
                ImgPath = book.ImgCover,
 
            };
            return View(editBookViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditBookViewModel editBookViewModel)
        {
            var result = await _bookServices.UpdateBookAsync(editBookViewModel);
            if (!result)
            {
                TempData["Error"] = "Error while updating entity on database";
            }
            return RedirectToAction("Index");

        }
    }

}

Biblioteca/Controllers/LoanController.cs
using Biblioteca.Services;
using Biblioteca.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Biblioteca.Controllers
{
    public class LoanController : Controller
    {
        private readonly LoanServices _loanServices;
      

        public LoanController(LoanServices loanServices)
        {
            _loanServices = loanServices;
        
        }
        public async Task<IActionResult> Index()
        {
            var loans = await _loanServices.GetAllLoansAsync();
            return View(loans);
        }


        public IActionResult Add(Guid id)
        {
            var add = new AddLoanViewModel() {BookId=id};


            return View(add);
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddLoanViewModel addLoanViewModel)
        {
            if (!ModelState.IsValid)
            {
                TempData["Error"] = "Error while saving entity to database";
                return RedirectToAction("Index");
            }
            var result = await _loanServices.AddLoanAsync(addLoanViewModel);
            if (!result)
            {
                TempData["Error"] = "Error while saving entity to database";
            }
            return RedirectToAction("Index");
        }

    }
}

Biblioteca/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Biblioteca</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Biblioteca.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-toggleable-md border-bottom box-shadow mb-3" style=" background-color: #00204a;">
            <div class="container-fluid">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">Library</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon">
                        <i class="bi bi-list pt-1 fs-3 text-white"></i>
                    </span>
                </button>
                <div class="navbar-collapse collapse d-md-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Book" asp-action="Index">Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Loan" asp-action="Index">Loan</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Biblioteca - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>